/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;

import ui.school.*;

/**
 *
 * @author nagashreeseshadri
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolJPanel
     */
    public AdminWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageStudents = new javax.swing.JButton();
        lblStudentInfoHeading = new javax.swing.JLabel();
        lblStudentInfoHeading1 = new javax.swing.JLabel();
        btnManageTeachers = new javax.swing.JButton();
        btnManageImmunization = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageStudents.setText("Manage Students");
        add(btnManageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 96, 183, -1));

        lblStudentInfoHeading.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStudentInfoHeading.setText("Administration ");
        add(lblStudentInfoHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 56, -1, -1));

        lblStudentInfoHeading1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStudentInfoHeading1.setText("Welcome to the Day Care");
        add(lblStudentInfoHeading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 16, -1, -1));

        btnManageTeachers.setText("Manage Teachers");
        add(btnManageTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 143, 183, -1));

        btnManageImmunization.setText("Manage Immunization");
        btnManageImmunization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageImmunizationActionPerformed(evt);
            }
        });
        add(btnManageImmunization, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageImmunizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageImmunizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageImmunizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageImmunization;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnManageTeachers;
    private javax.swing.JLabel lblStudentInfoHeading;
    private javax.swing.JLabel lblStudentInfoHeading1;
    // End of variables declaration//GEN-END:variables
}
