/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;

/**
 *
 * @author nagashreeseshadri
 */
public class ImmunizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Immunization
     */
    public ImmunizationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInfoHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImmunizationInfo = new javax.swing.JTable();
        btnUploadCSV = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentInfoHeading.setText("Immunization Information");
        add(lblStudentInfoHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 6, -1, -1));

        tblImmunizationInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Immunization ID", "Immunization Name", "Student ID", "Total Doses", "Doses Taken", "Recent Vaccination Date", "Vaccination Status", "Next Vaccination Date"
            }
        ));
        jScrollPane1.setViewportView(tblImmunizationInfo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, 1024, 157));

        btnUploadCSV.setText("Upload CSV");
        btnUploadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCSVActionPerformed(evt);
            }
        });
        add(btnUploadCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 286, 158, -1));

        btnView.setText("View");
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 286, -1, -1));

        btnAdd.setText("Add");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 286, -1, -1));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 286, -1, -1));

        btnDelete.setText("Delete");
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 286, -1, -1));

        btnBack.setText("<<Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 18, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadCSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadCSV;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStudentInfoHeading;
    private javax.swing.JTable tblImmunizationInfo;
    // End of variables declaration//GEN-END:variables
}
