/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view.ui.admin;

import edu.neu.csye6200.controller.ImmunizationController;
import edu.neu.csye6200.model.Immunization;
import edu.neu.csye6200.model.Student;
import edu.neu.csye6200.utils.ConvertUtil;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nagashreeseshadri
 */
public class TrackImmunizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Immunization
     */
    private JPanel userProcessContainer;
    long studentId;

//    public TrackImmunizationJPanel(JPanel userProcessContainer) {
//        initComponents();
//
//        this.userProcessContainer = userProcessContainer;
//    }

    public TrackImmunizationJPanel(JPanel userProcessContainer, long studentId) {
        this.userProcessContainer = userProcessContainer;
        this.studentId = studentId;
        initComponents();
        populateImmTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInfoHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImmunizationInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblStudentInfoHeading.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblStudentInfoHeading.setText("Track Student Immunization Information");

        tblImmunizationInfo.setBackground(new java.awt.Color(153, 255, 255));
        tblImmunizationInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Dose 1 ID", "Date for Dose 1", "Dose 2 ID", "Date for Dose 2", "Dose 3 ID", "Dose 3 Date", "Dose 4 ID", "Dose 4 Date"
            }
        ));
        jScrollPane1.setViewportView(tblImmunizationInfo);

        btnRefresh.setBackground(new java.awt.Color(153, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");

        btnBack.setBackground(new java.awt.Color(153, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/view/ui/Images/banner-enrollment-1.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 1130, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(352, 352, 352)
                        .addComponent(lblStudentInfoHeading))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStudentInfoHeading)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateImmTable(){
        DefaultTableModel model = (DefaultTableModel) tblImmunizationInfo.getModel();
        ImmunizationController controller = new ImmunizationController();
        List<Immunization> immunizations = controller.getImmunizationByIdDao(studentId);
        for(Immunization vaccine: immunizations){
            String vaccineName = vaccine.getImmunizationName();
            String dose1Id = ConvertUtil.longToString(vaccine.getDoseId1());
            String dose1Date = ConvertUtil.dateToString(vaccine.getDoseDate1());
            String dose2Id = ConvertUtil.longToString(vaccine.getDoseId2());
            String dose2Date = ConvertUtil.dateToString(vaccine.getDoseDate2());
            String dose3Id = ConvertUtil.longToString(vaccine.getDoseId3());
            String dose3Date = ConvertUtil.dateToString(vaccine.getDoseDate3());
            String dose4Id = ConvertUtil.longToString(vaccine.getDoseId4());
            String dose4Date = ConvertUtil.dateToString(vaccine.getDoseDate4());
            if(dose1Id.equals("0")){
                dose1Id = "";
            }
            if(dose2Id.equals("0")){
                dose2Id = "";
            }
            if(dose3Id.equals("0")){
                dose3Id = "";
            }
            if(dose4Id.equals("0")){
                dose4Id = "";
            }
            Object[] row = {vaccineName, dose1Id, dose1Date, dose2Id, dose2Date, dose3Id, dose3Date, dose4Id, dose4Date};
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStudentInfoHeading;
    private javax.swing.JTable tblImmunizationInfo;
    // End of variables declaration//GEN-END:variables
}




